# Generated by Django 4.1.7 on 2023-02-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisermangementapp', '0002_blogposter_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposter',
            name='back_ground_img_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
