# Generated by Django 4.1.7 on 2023-02-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisermangementapp', '0003_blogposter_back_ground_img_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogposter',
            name='video',
        ),
        migrations.AddField(
            model_name='blogposter',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='blogposter',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='blogposter',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='blogposter',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='blogposter',
            name='article',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
