# Generated by Django 4.1.7 on 2023-02-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisermangementapp', '0005_rename_image1_blogposter_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogposter',
            old_name='images',
            new_name='images1',
        ),
        migrations.AddField(
            model_name='blogposter',
            name='images2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='blogposter',
            name='images3',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='blogposter',
            name='images4',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
